name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    name: Validate code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Verify dependencies
        run: go mod verify
      - name: Install dependencies
        run: |
          go get .
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Run staticcheck
        run: staticcheck ./...
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint ./...
      - name: Test with the Go CLI
        run: go test -race -vet=off ./...
